spring.application.name=hospitalManagement
#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=postgres
spring.datasource.password=Password@123
spring.jpa.hibernate.ddl-auto= create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path= /api/v1
# If we want hard coded data to be stored in our local code repo -- data.sql
#Need to comment spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

#Spring Security
#spring.security.user.name=jitu
#spring.security.user.password=pass

#token string

jwt.secretKey=asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyasi8df7asdf87987g98a7sg986a89sdf7y